function vals=glc_test_controldlg()
    cvals = struct('numval', pi, ...
                   'strval', 'Hello, world!', ...
                   'boolval', true, ...
                   'selval',int32(3), ...
                   'justastr',char(0), ...  % char array containing ASCII NULs: static string
                   'keyb',uint32(' '));
    cdesc = struct('key', {'numval','strval','boolval','selval','justastr','keyb'}, ...
                   'name', { ...
                       'A great constant', 'A greeting', 'To be or not to be', 'Free choice', ...
                       'Some boldface text', 'Pick a key' }, ...
                   'extra',[]);
    % numeric values need some extra info
    cdesc(1).extra = struct('format','%.03f', ...
                            'updownfunc',@(ov,dir)min(max(0, ov+dir/10), 4));
    cdesc(4).extra = {'Chicken', 'Beef', 'Dog'};
    cdesc(5).extra = true;  % highlight the text

    [vals,ok]=glc_listdlg('ControlVals',cvals, 'ControlDesc',cdesc, 'ListSize',[320 200], ...
                          'ControlCb','fprintf(''glc_test_controldlg.m: %s\n'', cvals.strval)', ...
                          'Name','Control Dialog Test');
end
